### ISSUE TITLE
Add auto-archiving posts to the CMS

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#2]
As a regular user, I would like to time sensitive posts to be automatically archived so I can have a news feed with the most pertinent information.

## Tasks
- [ ] Consider adding an attribute to posts in the CMS with an end date
- [ ] Update the template to not render posts with the attribute

## Acceptance criteria
- [ ] When I add a post with an end date and the date passes, the post is hidden from the primary news feed but can be found in the archive.
