### ISSUE TITLE
Draw draft frontend sketches

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#3]
As a frontend developer, I want to see rough sketches of different website layouts so that we can decide on a clean and sensible user interface.

## Tasks
- [x] Draw as many sketches as we can
- [x] Label elements (what function does this element have, important colours or features)
- [x] Consider elements such as:
- Search functionality
- Reading posts
- Edit
- Categorisation
- Other features e.g. payment platform

## Acceptance criteria
- [x] Deliver at least 3 total well labelled draft sketches of possible website layouts
