### ISSUE TITLE
Investigate backend frameworks

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#4]
As a backend developer, I want to investigate backend frameworks so that I can reduce the load of writing a backend service.

## Tasks
- [x] Investigate backend frameworks like Gin, Hugo or Revel and others
- [x] Write a simple feature comparison table between each framework 

## Acceptance criteria
- [x] Deliver a feature comparison table between the frameworks and provide an informed and discussed decision statement about which framework(s) to use
