### ISSUE TITLE
Learn Golang

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#5]
As a developer, I want to gain familiarity with the language that unifies backend and frontend so I can deliver a good product more efficiently.

## Tasks
- [x] Write a simple Markdown blog post server in Golang

**[Here](https://jonathanmh.com/creating-simple-markdown-blog-go-gin/)** you can find jonathanmh's excellent guide I used at a reference. Follow this first - it will help you figure out the basic logic behind the project.

---
Some further areas to research if you are stuck on specific points in the tutorial are (and/or possible steps):
- [x] Learn about **one possible way** to package your Go project by reading https://github.com/golang-standards/project-layout

- [x] Learn about [Golang modules](https://blog.golang.org/using-go-modules) (don't use dep) and how they're used in parallel with Golang Standard Layout at https://github.com/golang-standards/project-layout/issues/18. Thoughts about this approach?

- [x] Learn how to serve `html/template` files (e.g in the HTTP framework https://github.com/gin-gonic/gin)

- [x] Learn how to serve static files like CSS and images

- [x] Learn about routers (not the physical device)/middleware

- [x] Learn about [Markdown](https://daringfireball.net/projects/markdown/)

- [x] Learn how to parse Markdown (russross'  https://github.com/russross/blackfriday is a great place to start)

- [x] Learn about Golang slices etc.

- *Bonus points: Add a YAML frontmatter processor*

You can see how I approached it here: https://github.com/gawdn/csesoc-web-team-almanac (a little quickly done & not yet finished!)

## Acceptance criteria
- [x] When I go to the root directory `/` of the site I see a page of links with all the posts
- [x] When I go to `/posts/INSERT_POST_NAME_HERE` I get the post I can read
- [x] The posts are styled with CSS served from a directory (not inline!)
- [x] I can add posts by simply adding a markdown file to a directory (shouldn't have to edit code)
- [x] I can add images to a directory and link them in my markdown posts (e.g `![my caption](/static/images/cactus.png)`)
