### ISSUE TITLE
Investigate databases

### ISSUE THREAD

**Issue by gawdn** [csesoc/csesoc.unsw.edu.au#6]
As a backend developer, I want to investigate database solutions so I can weigh the benefits and pitfalls of each solution for storing data.

## Tasks
- [x] Investigate database solutions like MySQL, PostgreSQL, DynamoDB, MongoDB
- [x] Write a simple feature comparison table between each database  

## Acceptance criteria
- [x] Deliver a feature comparison table between the databases
